name: rick_morty_test_ex
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  git: ^2.3.2
  google_fonts: ^8.0.2
  http: ^1.6.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.11.1
  build_runner: ^2.13.0

flutter:
  uses-material-design: true
